/**
 * Integration tests for F5: Gaming Item Trade
 *
 * Full pipeline: ZK proof generation → on-chain verification
 * Uses the real Solidity verifier generated by snarkjs (not mock).
 */

const { expect } = require("chai");
const { ethers } = require("hardhat");
const snarkjs = require("snarkjs");
const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const {
  poseidonHash,
  randomSecretKey,
  getPublicKey,
  init: initBabyJub,
} = require("../scripts/lib/circomlibBabyJub");

const CIRCUIT_NAME = "gaming_item_trade";
const BUILD_DIR = path.join(__dirname, "../circuits/build", CIRCUIT_NAME);
const WASM_PATH = path.join(BUILD_DIR, `${CIRCUIT_NAME}_js`, `${CIRCUIT_NAME}.wasm`);
const ZKEY_PATH = path.join(BUILD_DIR, `${CIRCUIT_NAME}.zkey`);

function checkBuildFiles() {
  return fs.existsSync(ZKEY_PATH) && fs.existsSync(WASM_PATH);
}

function formatProofForSolidity(proof) {
  return {
    a: [proof.pi_a[0], proof.pi_a[1]],
    b: [
      [proof.pi_b[0][1], proof.pi_b[0][0]],
      [proof.pi_b[1][1], proof.pi_b[1][0]],
    ],
    c: [proof.pi_c[0], proof.pi_c[1]],
  };
}

function toHex32(bn) {
  return "0x" + BigInt(bn).toString(16).padStart(64, "0");
}

let _itemIdCounter = 0;

/**
 * Generate all cryptographic material for a trade.
 * Returns both circuit inputs and formatted proof.
 */
async function setupTrade(options = {}) {
  const sellerSk = options.sellerSk || await randomSecretKey();
  const sellerPk = await getPublicKey(sellerSk);

  const buyerSk = options.buyerSk || await randomSecretKey();
  const buyerPk = await getPublicKey(buyerSk);

  _itemIdCounter++;
  const itemId = options.itemId || BigInt(_itemIdCounter);
  const itemType = options.itemType || BigInt(3);
  const itemAttributes = options.itemAttributes || BigInt(9999);
  const gameId = options.gameId || BigInt(42);
  const price = options.price !== undefined ? BigInt(options.price) : BigInt(1000);
  const paymentToken = options.paymentToken || BigInt(1);
  const oldSalt = BigInt("0x" + crypto.randomBytes(31).toString("hex"));
  const newSalt = BigInt("0x" + crypto.randomBytes(31).toString("hex"));
  const paymentSalt = BigInt("0x" + crypto.randomBytes(31).toString("hex"));

  const oldItemHash = await poseidonHash([
    sellerPk.x, sellerPk.y, itemId, itemType, itemAttributes, gameId, oldSalt,
  ]);
  const newItemHash = await poseidonHash([
    buyerPk.x, buyerPk.y, itemId, itemType, itemAttributes, gameId, newSalt,
  ]);
  const nullifier = await poseidonHash([itemId, oldSalt, sellerSk]);

  let paymentNoteHash;
  if (price === 0n) {
    paymentNoteHash = 0n;
  } else {
    paymentNoteHash = await poseidonHash([
      sellerPk.x, sellerPk.y, price, paymentToken, paymentSalt,
    ]);
  }

  const circuitInputs = {
    oldItemHash: oldItemHash.toString(),
    newItemHash: newItemHash.toString(),
    paymentNoteHash: paymentNoteHash.toString(),
    gameId: gameId.toString(),
    nullifier: nullifier.toString(),
    sellerPkX: sellerPk.x.toString(),
    sellerPkY: sellerPk.y.toString(),
    sellerSk: sellerSk.toString(),
    oldSalt: oldSalt.toString(),
    buyerPkX: buyerPk.x.toString(),
    buyerPkY: buyerPk.y.toString(),
    newSalt: newSalt.toString(),
    itemId: itemId.toString(),
    itemType: itemType.toString(),
    itemAttributes: itemAttributes.toString(),
    price: price.toString(),
    paymentToken: paymentToken.toString(),
    paymentSalt: paymentSalt.toString(),
  };

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    circuitInputs, WASM_PATH, ZKEY_PATH
  );

  const formattedProof = formatProofForSolidity(proof);

  return {
    circuitInputs,
    proof: formattedProof,
    publicSignals,
    oldItemHash: toHex32(oldItemHash),
    newItemHash: toHex32(newItemHash),
    paymentNoteHash: toHex32(paymentNoteHash),
    gameId,
    itemId,
    nullifier: toHex32(nullifier),
    sellerSk,
    buyerSk,
    sellerPk,
    buyerPk,
    // Keep for chained trades
    itemType,
    itemAttributes,
    price,
    paymentToken,
    newSalt,
  };
}

/**
 * Full P2P trade helper: register → list → purchase → execute
 */
async function doFullTrade(contract, token, tx, sellerSigner, buyerSigner, priceWei) {
  const contractAddr = await contract.getAddress();

  // 1. Register item
  await contract.connect(sellerSigner).registerItem(
    tx.oldItemHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
  );

  // 2. List item
  await contract.connect(sellerSigner).listItem(
    tx.oldItemHash, tx.gameId, tx.itemId, priceWei
  );
  const listingId = (await contract.nextListingId()) - 1n;

  // 3. Buyer approves + purchases
  await token.connect(buyerSigner).approve(contractAddr, priceWei);
  const buyerPkX = BigInt(tx.circuitInputs.buyerPkX);
  const buyerPkY = BigInt(tx.circuitInputs.buyerPkY);
  await contract.connect(buyerSigner).purchaseItem(listingId, buyerPkX, buyerPkY);

  // 4. Seller executes trade
  await contract.connect(sellerSigner).executeTradeForBuyer(
    listingId,
    tx.proof.a, tx.proof.b, tx.proof.c,
    tx.newItemHash, tx.paymentNoteHash, tx.nullifier,
    ethers.toUtf8Bytes("new-enc")
  );

  return listingId;
}

describe("F5: Gaming Item Trade - Integration", function () {
  this.timeout(300000);

  let gamingItemTrade;
  let mockToken;
  let owner, sellerAcc, buyerAcc, thirdPartyAcc;
  let hasBuild;

  before(async function () {
    await initBabyJub();
    hasBuild = checkBuildFiles();
    if (!hasBuild) {
      console.log("\n  ⚠️  Skipping integration tests: circuit not fully compiled");
      console.log("     Run: node scripts/compile-circuit.js gaming_item_trade\n");
      this.skip();
    }

    const verifierPath = path.join(__dirname, "../contracts/verifiers/GamingItemTradeVerifier.sol");
    if (!fs.existsSync(verifierPath)) {
      console.log("\n  ⚠️  Skipping: Solidity verifier not generated yet");
      this.skip();
    }
  });

  beforeEach(async function () {
    if (!hasBuild) this.skip();

    [owner, sellerAcc, buyerAcc, thirdPartyAcc] = await ethers.getSigners();

    // Deploy MockERC20 and fund accounts
    const MockERC20 = await ethers.getContractFactory("MockERC20");
    mockToken = await MockERC20.deploy();
    await mockToken.mint(sellerAcc.address, ethers.parseEther("100000"));
    await mockToken.mint(buyerAcc.address, ethers.parseEther("100000"));
    await mockToken.mint(thirdPartyAcc.address, ethers.parseEther("100000"));

    let verifierAddress;
    try {
      const Verifier = await ethers.getContractFactory(
        "contracts/verifiers/GamingItemTradeVerifier.sol:Groth16Verifier"
      );
      const verifier = await Verifier.deploy();
      verifierAddress = await verifier.getAddress();
    } catch (e) {
      const MockVerifier = await ethers.getContractFactory("MockGamingItemTradeVerifier");
      const mockVerifier = await MockVerifier.deploy();
      verifierAddress = await mockVerifier.getAddress();
    }

    const GamingItemTrade = await ethers.getContractFactory("GamingItemTrade");
    gamingItemTrade = await GamingItemTrade.deploy(
      verifierAddress,
      await mockToken.getAddress()
    );
  });

  describe("Full pipeline: proof generation → on-chain verification", function () {
    it("should complete full P2P trade with real ZK proof (paid)", async function () {
      const priceWei = ethers.parseEther("100");
      const tx = await setupTrade({ price: 1000 });

      const sellerBefore = await mockToken.balanceOf(sellerAcc.address);
      const buyerBefore = await mockToken.balanceOf(buyerAcc.address);

      await doFullTrade(gamingItemTrade, mockToken, tx, sellerAcc, buyerAcc, priceWei);

      expect(await gamingItemTrade.getNoteState(tx.oldItemHash)).to.equal(2); // Spent
      expect(await gamingItemTrade.getNoteState(tx.newItemHash)).to.equal(1); // Valid
      expect(await gamingItemTrade.isNullifierUsed(tx.nullifier)).to.be.true;

      // Verify payment flows
      const sellerAfter = await mockToken.balanceOf(sellerAcc.address);
      const buyerAfter = await mockToken.balanceOf(buyerAcc.address);
      expect(sellerAfter - sellerBefore).to.equal(priceWei);
      expect(buyerBefore - buyerAfter).to.equal(priceWei);
    });

    it("should complete full P2P trade as gift (price=0)", async function () {
      const priceWei = ethers.parseEther("1"); // minimal price (gift uses price=0 in ZK, but needs >0 on-chain)
      const tx = await setupTrade({ price: 0 });

      // Gift: ZK circuit uses price=0, but on-chain listing still has a token price for escrow
      // Use a minimal price for on-chain, keeping paymentNoteHash=0 in ZK
      const contractAddr = await gamingItemTrade.getAddress();

      await gamingItemTrade.connect(sellerAcc).registerItem(
        tx.oldItemHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
      );
      await gamingItemTrade.connect(sellerAcc).listItem(
        tx.oldItemHash, tx.gameId, tx.itemId, priceWei
      );
      const listingId = (await gamingItemTrade.nextListingId()) - 1n;

      await mockToken.connect(buyerAcc).approve(contractAddr, priceWei);
      const buyerPkX = BigInt(tx.circuitInputs.buyerPkX);
      const buyerPkY = BigInt(tx.circuitInputs.buyerPkY);
      await gamingItemTrade.connect(buyerAcc).purchaseItem(listingId, buyerPkX, buyerPkY);

      await gamingItemTrade.connect(sellerAcc).executeTradeForBuyer(
        listingId,
        tx.proof.a, tx.proof.b, tx.proof.c,
        tx.newItemHash, tx.paymentNoteHash, tx.nullifier,
        ethers.toUtf8Bytes("new-enc")
      );

      expect(await gamingItemTrade.getNoteState(tx.oldItemHash)).to.equal(2);
      expect(await gamingItemTrade.getNoteState(tx.newItemHash)).to.equal(1);
    });

    it("should allow chained trades (A → B → C)", async function () {
      const priceWei = ethers.parseEther("100");

      // First trade: A (sellerAcc) → B (buyerAcc)
      const tx1 = await setupTrade();

      await doFullTrade(gamingItemTrade, mockToken, tx1, sellerAcc, buyerAcc, priceWei);

      expect(await gamingItemTrade.getNoteState(tx1.oldItemHash)).to.equal(2); // Spent
      expect(await gamingItemTrade.getNoteState(tx1.newItemHash)).to.equal(1); // Valid

      // Second trade: B (buyerAcc) → C (thirdPartyAcc)
      // B owns tx1.newItemHash; generate proof as B
      const ownerCSk = await randomSecretKey();
      const ownerCPk = await getPublicKey(ownerCSk);
      const ownerBPk = tx1.buyerPk;
      const ownerBSk = tx1.buyerSk;

      const newSalt2 = BigInt("0x" + crypto.randomBytes(31).toString("hex"));
      const paymentSalt2 = BigInt("0x" + crypto.randomBytes(31).toString("hex"));
      const bSalt = tx1.newSalt;
      const { itemId, itemType, itemAttributes, gameId } = tx1;
      const price2 = BigInt(500);
      const paymentToken2 = BigInt(1);

      const newItemHash2 = await poseidonHash([
        ownerCPk.x, ownerCPk.y, itemId, itemType, itemAttributes, gameId, newSalt2,
      ]);
      const nullifier2 = await poseidonHash([itemId, bSalt, ownerBSk]);
      const paymentNoteHash2 = await poseidonHash([
        ownerBPk.x, ownerBPk.y, price2, paymentToken2, paymentSalt2,
      ]);

      const circuitInputs2 = {
        oldItemHash: tx1.circuitInputs.newItemHash,
        newItemHash: newItemHash2.toString(),
        paymentNoteHash: paymentNoteHash2.toString(),
        gameId: gameId.toString(),
        nullifier: nullifier2.toString(),
        sellerPkX: ownerBPk.x.toString(),
        sellerPkY: ownerBPk.y.toString(),
        sellerSk: ownerBSk.toString(),
        oldSalt: bSalt.toString(),
        buyerPkX: ownerCPk.x.toString(),
        buyerPkY: ownerCPk.y.toString(),
        newSalt: newSalt2.toString(),
        itemId: itemId.toString(),
        itemType: itemType.toString(),
        itemAttributes: itemAttributes.toString(),
        price: price2.toString(),
        paymentToken: paymentToken2.toString(),
        paymentSalt: paymentSalt2.toString(),
      };

      const { proof: proof2 } = await snarkjs.groth16.fullProve(
        circuitInputs2, WASM_PATH, ZKEY_PATH
      );
      const fp2 = formatProofForSolidity(proof2);

      const newItemHash2Hex = toHex32(newItemHash2);
      const nullifier2Hex = toHex32(nullifier2);
      const paymentNoteHash2Hex = toHex32(paymentNoteHash2);

      const contractAddr = await gamingItemTrade.getAddress();

      // B lists the note they received from first trade
      await gamingItemTrade.connect(buyerAcc).listItem(
        tx1.newItemHash, gameId, itemId, priceWei
      );
      const listingId2 = (await gamingItemTrade.nextListingId()) - 1n;

      // C purchases
      await mockToken.connect(thirdPartyAcc).approve(contractAddr, priceWei);
      await gamingItemTrade.connect(thirdPartyAcc).purchaseItem(
        listingId2, ownerCPk.x, ownerCPk.y
      );

      // B executes trade for C
      await gamingItemTrade.connect(buyerAcc).executeTradeForBuyer(
        listingId2,
        fp2.a, fp2.b, fp2.c,
        newItemHash2Hex, paymentNoteHash2Hex, nullifier2Hex,
        ethers.toUtf8Bytes("enc-c")
      );

      expect(await gamingItemTrade.getNoteState(tx1.newItemHash)).to.equal(2); // Spent
      expect(await gamingItemTrade.getNoteState(newItemHash2Hex)).to.equal(1); // Valid
    });
  });

  describe("Security: rejection cases", function () {
    it("should reject double-spend (same nullifier)", async function () {
      const priceWei = ethers.parseEther("100");
      const tx = await setupTrade();
      const contractAddr = await gamingItemTrade.getAddress();

      await doFullTrade(gamingItemTrade, mockToken, tx, sellerAcc, buyerAcc, priceWei);

      // Set up a second listing (new item)
      const tx2 = await setupTrade();
      await gamingItemTrade.connect(sellerAcc).registerItem(
        tx2.oldItemHash, tx2.gameId, tx2.itemId, ethers.toUtf8Bytes("enc")
      );
      await gamingItemTrade.connect(sellerAcc).listItem(
        tx2.oldItemHash, tx2.gameId, tx2.itemId, priceWei
      );
      const listingId2 = (await gamingItemTrade.nextListingId()) - 1n;
      await mockToken.connect(buyerAcc).approve(contractAddr, priceWei);
      await gamingItemTrade.connect(buyerAcc).purchaseItem(
        listingId2, BigInt(tx2.circuitInputs.buyerPkX), BigInt(tx2.circuitInputs.buyerPkY)
      );

      // Try to reuse nullifier from first trade
      await expect(
        gamingItemTrade.connect(sellerAcc).executeTradeForBuyer(
          listingId2,
          tx2.proof.a, tx2.proof.b, tx2.proof.c,
          tx2.newItemHash, tx2.paymentNoteHash, tx.nullifier, // reused nullifier
          ethers.toUtf8Bytes("enc")
        )
      ).to.be.revertedWith("Nullifier already used");
    });

    it("should reject trade of already-spent note", async function () {
      const priceWei = ethers.parseEther("100");
      const tx = await setupTrade();

      await doFullTrade(gamingItemTrade, mockToken, tx, sellerAcc, buyerAcc, priceWei);

      // The old note is now spent — listing a new listing for it would fail on noteExists
      await expect(
        gamingItemTrade.connect(sellerAcc).listItem(
          tx.oldItemHash, tx.gameId, tx.itemId, priceWei
        )
      ).to.be.revertedWith("Note does not exist or already spent");
    });

    it("should reject duplicate item registration", async function () {
      const tx = await setupTrade();

      await gamingItemTrade.connect(sellerAcc).registerItem(
        tx.oldItemHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
      );

      const fakeHash = ethers.keccak256(ethers.toUtf8Bytes("different-hash"));
      await expect(
        gamingItemTrade.connect(sellerAcc).registerItem(
          fakeHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
        )
      ).to.be.revertedWith("Item already registered");
    });

    it("should reject duplicate note hash registration", async function () {
      const tx = await setupTrade();

      await gamingItemTrade.connect(sellerAcc).registerItem(
        tx.oldItemHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
      );

      await expect(
        gamingItemTrade.connect(sellerAcc).registerItem(
          tx.oldItemHash, 999n, 999n, ethers.toUtf8Bytes("enc")
        )
      ).to.be.revertedWith("Note already exists");
    });
  });

  describe("Events", function () {
    it("should emit ItemRegistered event", async function () {
      const tx = await setupTrade();

      await expect(
        gamingItemTrade.connect(sellerAcc).registerItem(
          tx.oldItemHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
        )
      ).to.emit(gamingItemTrade, "ItemRegistered");
    });

    it("should emit ItemListed event", async function () {
      const tx = await setupTrade();
      await gamingItemTrade.connect(sellerAcc).registerItem(
        tx.oldItemHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
      );

      await expect(
        gamingItemTrade.connect(sellerAcc).listItem(
          tx.oldItemHash, tx.gameId, tx.itemId, ethers.parseEther("100")
        )
      ).to.emit(gamingItemTrade, "ItemListed");
    });

    it("should emit ItemTradeCompleted event on full trade", async function () {
      const priceWei = ethers.parseEther("100");
      const tx = await setupTrade();
      const contractAddr = await gamingItemTrade.getAddress();

      await gamingItemTrade.connect(sellerAcc).registerItem(
        tx.oldItemHash, tx.gameId, tx.itemId, ethers.toUtf8Bytes("enc")
      );
      await gamingItemTrade.connect(sellerAcc).listItem(
        tx.oldItemHash, tx.gameId, tx.itemId, priceWei
      );
      const listingId = (await gamingItemTrade.nextListingId()) - 1n;
      await mockToken.connect(buyerAcc).approve(contractAddr, priceWei);
      await gamingItemTrade.connect(buyerAcc).purchaseItem(
        listingId, BigInt(tx.circuitInputs.buyerPkX), BigInt(tx.circuitInputs.buyerPkY)
      );

      await expect(
        gamingItemTrade.connect(sellerAcc).executeTradeForBuyer(
          listingId,
          tx.proof.a, tx.proof.b, tx.proof.c,
          tx.newItemHash, tx.paymentNoteHash, tx.nullifier,
          ethers.toUtf8Bytes("enc")
        )
      ).to.emit(gamingItemTrade, "ItemTradeCompleted");
    });
  });
});
