import { Contract, type JsonRpcSigner } from "ethers";
import type { ContractName } from "./types";
import deployedAddresses from "../config/deployedAddresses.json";

// ABI imports (generated by copy-frontend-assets.js)
import PrivateNFTAbi from "../abi/PrivateNFT.json";
import LootBoxOpenAbi from "../abi/LootBoxOpen.json";
import GamingItemTradeAbi from "../abi/GamingItemTrade.json";
import CardDrawAbi from "../abi/CardDraw.json";

const ABI_MAP: Record<ContractName, unknown[]> = {
  PrivateNFT: PrivateNFTAbi,
  LootBoxOpen: LootBoxOpenAbi,
  GamingItemTrade: GamingItemTradeAbi,
  CardDraw: CardDrawAbi,
};

const ADDRESS_MAP: Record<ContractName, string> = {
  PrivateNFT: (deployedAddresses as Record<string, string>).privateNFT,
  LootBoxOpen: (deployedAddresses as Record<string, string>).lootBoxOpen,
  GamingItemTrade: (deployedAddresses as Record<string, string>).gamingItemTrade,
  CardDraw: (deployedAddresses as Record<string, string>).cardDraw,
};

/**
 * Get a contract instance connected to a signer
 */
export function getContract(name: ContractName, signer: JsonRpcSigner): Contract {
  const address = ADDRESS_MAP[name];
  const abi = ABI_MAP[name];
  if (!address) throw new Error(`No deployed address for ${name}`);
  return new Contract(address, abi as never[], signer);
}
